= {project_name} Notebook
:stem: latexmath
:page-jupyter: true
:page-plotly: true
:page-mpl3d: true

[.lead]
This is a Jupyter notebook for the {project_name} project.

== Introduction

You write your notebook in AsciiDoc including LaTeX math and thanks to the `:page-jupyter: true` attribute, the notebook is converted to a Jupyter notebook when the book is built.

[NOTE]
====
For the doc contributors, to run the notebook in {vscode}:

* select the kernel to use: use the previously created virtual env

For the others, you need to download the notebook and run it in a separate way.
To test the notebook, you can either use:

* a local jupyter installation:
** create a python virtual environment
** install the requested packages
** start the the notebook

* or a container (eg. docker image)
** get the container
** run the container with mounting ...

====

== Code cells

You can include code cells in your notebook using the `[source,python]` block macro.

[%dynamic%open,python]
----
import sys, os
print("Hello, world!")
----


== {feelpp} Code cells

You can include {feelpp} code cells in your notebook using the `[source,python]` block macro.
Use `[%dynamic%open,python]` to view the output.

[%dynamic%open,python]
----
import feelpp.core as fppc
app = fppc.Environment(["myapp"],config=fppc.globalRepository("myapp"))

import os
print(f'pwd: {os.getcwd()}')

geo=fppc.download( "github:{repo:feelpp,path:feelpp/quickstart/laplacian/cases/feelpp2d/feelpp2d.geo}", worldComm=app.worldCommPtr() )[0]
print(f"geo file: {geo}")
mesh = fppc.load(fppc.mesh(dim=2,realdim=2), geo, 0.1)

Xh=fppc.functionSpace(mesh=mesh, space="Pchv")
f = Xh.element()
f.on(range=fppc.elements(mesh),expr=fppc.expr("{sin(pi*x)*sin(pi*y),cos(pi*x)*cos(pi*y)}:x:y",row=2,col=1))
e= fppc.exporter(mesh=mesh)
e.add("f",f)
e.save()
----

To visualize the result, you can use the `pyvista` package. But, before, you need to fix the {ensight} case file as follows:

[%dynamic%open,python]
----
print(f'pwd: {os.getcwd()}')

# remove 'change_coords_only' after GEOMETRY/model filename.geo[***]
outfile = open('exports/ensightgold/Exporter/tmp.case', 'w')
with open("exports/ensightgold/Exporter/Exporter.case") as f:
    for line in f:
        print(f'line={line[:-1]}', end=" -> ")
        line = line.replace('change_coords_only', '')
        print(line[:-1])
        outfile.write(line)
    outfile.close()
----

Use `[%dynamic%raw%open,python]` to view the output:

[%dynamic%raw%open,python]
----
print(f'pwd: {os.getcwd()}')

import pyvista as pv
# uncomment the next line, if you cannot get the image
# pv.start_xvfb()
pv.set_jupyter_backend('static')
reader = pv.get_reader("exports/ensightgold/Exporter/tmp.case")
mesh = reader.read()
mesh.plot(scalars="f",cpos='xy',show_scalar_bar=False)
----

////
[%dynamic%raw%open,python]
----
# remove tmp file
import os
os.remove(outfile)
----
////

[NOTE]
=====
You may need to change the path to the ensight gold output file depending on your setup.
=====
